### ISSUE TITLE
redundant LOAD

### ISSUE THREAD

**Issue by TallTed** [OpenLinkSoftware/SPASQL-Utility-Showcase-Queries#2]
https://github.com/OpenLinkSoftware/SPASQL-Utility-Showcase-Queries/blob/12515b70b4e908d59e9c47fbf2f1d395c60c8362/loading-current-offers.sql#L9

https://github.com/OpenLinkSoftware/SPASQL-Utility-Showcase-Queries/blob/12515b70b4e908d59e9c47fbf2f1d395c60c8362/loading-current-offers.sql#L11

Line 11 appears to be redundant, effectively repeating line 9, given that --

```pre
$ curl -LI http://www.openlinksw.com/ontology/products
HTTP/1.1 303 See Other
...
Location: http://www.openlinksw.com/DAV/data/turtle/products.ttl
```

-- and that `http://www.openlinksw.com/DAV/data/turtle/products.ttl` dereferences to the same file as `http://www.openlinksw.com/data/turtle/products.ttl`

**Comment by TallTed** [comment]
@kidehen @openlink 

The lines are not identical, or I'd delete one.  Though the result of each  winds up being the same as the other today, I am not sure whether this will change in time, and thus whether the `LOAD` **should** come from --

* `http://www.openlinksw.com/ontology/products` (and thence `http://www.openlinksw.com/DAV/data/turtle/products.ttl`) or 

* `http://www.openlinksw.com/data/turtle/products.ttl`

**Comment by kidehen** [comment]
It should be: 
http://www.openlinksw.com/data/turtle/products.ttl
